spring:
  h2:
    console:
      enabled: true
  application:
    name: brief15
  datasource:
    url: jdbc:h2:mem:brief15
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: db/migration
    validate-on-migrate: true
    baseline-on-migrate: true